USE [master]
GO
/****** Object:  Database [xyz]    Script Date: 06-01-2024 18:45:24 ******/
CREATE DATABASE [xyz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'xyz', FILENAME = N'C:\Users\Lenovo\xyz.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'xyz1', FILENAME = N'C:\Users\Lenovo\xyz1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'xyz2', FILENAME = N'C:\Users\Lenovo\xyz2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'xyz3', FILENAME = N'C:\Users\Lenovo\xyz3.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'xyz_log', FILENAME = N'C:\Users\Lenovo\xyz_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [xyz] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [xyz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [xyz] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [xyz] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [xyz] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [xyz] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [xyz] SET ARITHABORT OFF 
GO
ALTER DATABASE [xyz] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [xyz] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [xyz] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [xyz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [xyz] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [xyz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [xyz] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [xyz] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [xyz] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [xyz] SET  DISABLE_BROKER 
GO
ALTER DATABASE [xyz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [xyz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [xyz] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [xyz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [xyz] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [xyz] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [xyz] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [xyz] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [xyz] SET  MULTI_USER 
GO
ALTER DATABASE [xyz] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [xyz] SET DB_CHAINING OFF 
GO
ALTER DATABASE [xyz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [xyz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [xyz] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [xyz] SET QUERY_STORE = OFF
GO
USE [xyz]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [xyz]
GO
/****** Object:  Table [dbo].[BRANCH]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BRANCH](
	[BRANCHID] [varchar](50) NULL,
	[DEGREEID] [int] NULL,
	[BRANCHNAME] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEGREE]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEGREE](
	[DEGREEID] [int] NULL,
	[DEGREENAME] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UAE]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UAE](
	[Roll] [int] NULL,
	[Name] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[Pick] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UDB]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UDB](
	[UserId] [int] NULL,
	[UserName] [varchar](50) NULL,
	[Password] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UDB1]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UDB1](
	[DateofBirth] [int] NULL,
	[Gender] [varchar](50) NULL,
	[Degree] [varchar](50) NULL,
	[EmailId] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[XZ]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[XZ](
	[Roll] [int] NULL,
	[Name] [varchar](50) NULL,
	[City] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[mypro]    Script Date: 06-01-2024 18:45:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create PROCEDURE [dbo].[mypro]
AS
BEGIN
select * from UDB1;
END;

GO
USE [master]
GO
ALTER DATABASE [xyz] SET  READ_WRITE 
GO
